services:
  mysql:
    image: mysql:8.0
    container_name: mysql_terracontab
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: terracontab
      MYSQL_USER: terracontab_user
      MYSQL_PASSWORD: secret123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  mysql_data:
